---
title: "Advanced R programming"
description: "Introduction to the overall course"
sort-key: "01"
format: 
  revealjs:
    theme: [simple, ../assets/custom.scss]
    df-print: paged
    code-line-numbers: true
editor: source
execute: 
  echo: true
---

# Welcome all!


# Organizational things {.smaller}


**Day 1:** Project Documentation, Workflow, Reproducibility

**Day 2:** Data cleaning & manipulation in the tidyverse

**Day 3:** Plotting

**Day 4:** Advanced R Programming 

**Day 5:** Build your own website 

<br>

. . .

**Exam:** pass fail exam - your website with one example project

**Due:** 30.06.23


## Day 1 {.smaller}

<br>

What we'll do today

1.  Introduction rounds

2.  Keeping your projects organized (project setup, data management, here::here(), ...)

3.  Good code

4.  Rmarkdown & Quarto for reports and analyses

5.  Package documentation ([{renv}]{.blue_highlight} / `sessionInfo()` ...)

6.  **Exercise**: work with reproducible documents 


# Introductions

- Your name
- Your proudest moment when learning / achieving something in R so far
- Your biggest R frustration 


# Talking about expectations

- What am I hoping this course to be?
- What are you hoping to learn in this course?
